# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9491b0505377865ba7614a3b8af6829f209d86743a4deecda6ef0eaa1baa8ddae9028c5072ff7feff92df8aba11ea05512fbf34c6c94f882641170ee9c36207

test:
  secret_key_base: facd8eca01a98dfc5c740b9fa3ad4d37993c220b8af4bf14b21d0c7000bcdd2e8429699ba801fc86cbcda394790f78bc6570f1bd87069c8010e28338ac904090

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
